name: Update Activity Graph
on:
  schedule:
    - cron: "0 0 * * *"  # Daily at 00:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Activity Graph
        run: |
          curl -o docs/activity-graph.svg \
          "https://activity-graph.herokuapp.com/graph?username=HanzlaSarwar327&theme=react-dark&area=true&hide_border=true&custom_title=Development+Activity"

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/activity-graph.svg
          git commit -m "Update activity graph [skip ci]"
          git push
