      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: HanzlaSarwar327
          outputs: dist/github-snake.svg

      - name: Commit & Push Snake Animation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-snake.svg || echo "No changes to commit"
          git commit -m "Update snake animation" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
