name: Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: HanzlaSarwar327
          outputs: |
            dist/github-snake.svg
      
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/github-snake.svg
          git commit -m "Update snake"
          git push
